// Generated by CoffeeScript 2.3.1
(function() {
  // comment
  /*
  Multiline comment
  In coffeescript
  */
  var csOutput, name;

  name = "Phil";

  csOutput = document.getElementById("csoutput");

  csOutput.innerHTML = `Hello ${name}`;

}).call(this);
