// Generated by CoffeeScript 2.3.1
(function() {
  // comment
  /*
  Multiline comment
  In coffeescript
  */
  var aString, csOutput, name;

  name = "Phil";

  csOutput = document.getElementById("csoutput");

  csOutput.innerHTML = `Hello ${name}<br/>`;

  aString = "I am a string";

  if (typeof aString === 'string') {
    csOutput.insertAdjacentHTML('beforeend', ' aString is a String <br>');
  }

}).call(this);
